### PR TITLE
Remove viper from the main page

### PR DESCRIPTION
**Pull request by EM4Volts**
Removes the couple lines in the html that reference viper. 
dont care if this is "unfair", viper is the sole cause of 99.6% of all issues that happen and are related to launchers, flightcore has linux support if thats another reason.

thank me later.

didnt test this, the file looks fine i think.

### CODE REVIEW

**Comment by Jan200101** [comment]
some personal thoughts on this:
- viper the easiest to install on the Steam Deck due to being on flatpak, however its Linux support is bare with launch support being non existant due to a lack of understanding of how its suppose to work and discontent with the proposed contributions of others.
- There appears to be little to no communication between Northstar contributors and Viper contributors, leading to changes being made that break Viper until an end-user reports it.
- No Viper contributor appears to be on the Northstar discord and practically none of the regulars make use of it, making it impossible to give proper support to users when an issue specific to it appears.

I am personally unhappy with Viper but I am neither for nor against this change.

**Comment by GeckoEidechse** [comment]
Before taking any action on this, I'd like to have @0neGal's input on this. Personally I cannot comment much on this, as given that I also wrote a mod-manager I clearly have a bias even if I try to be neutral.

I'm fully aware that no one can be expected to maintain their tool through changing Northstar updates but I'd like to start a discussion before deciding to outright remove Viper from the webpage (which is the point of this PR). We wanna make sure that we agree on a solution before we do any changes to avoid miscommunication and/or drama ^^

&nbsp;

> There appears to be little to no communication between Northstar contributors and Viper contributors, leading to changes being made that break Viper until an end-user reports it.

I'd like to point out that too my knowledge, all breaking changes have been communicated by me via GitHub issues (https://github.com/0neGal/viper/issues/223 https://github.com/0neGal/viper/issues/165 https://github.com/R2NorthstarTools/FlightCore/issues/288 https://github.com/R2Northstar/NorthstarLauncher/issues/505) unless I missed anything ^^"

**Comment by EM4Volts** [comment]
> Before taking any action on this, I'd like to have @0neGal's input on this. Personally I cannot comment much on this, as given that I also wrote a mod-manager I clearly have a bias even if I try to be neutral.
> 
> I'm fully aware that no one can be expected to maintain their tool through changing Northstar updates but I'd like to start a discussion before deciding to outright remove Viper from the webpage (which is the point of this PR). We wanna make sure that we agree on a solution before we do any changes to avoid miscommunication and/or drama ^^
> 
>  
> 
> > There appears to be little to no communication between Northstar contributors and Viper contributors, leading to changes being made that break Viper until an end-user reports it.
> 
> I'd like to point out that too my knowledge, all breaking changes have been communicated by me via GitHub issues ([0neGal/viper#223](https://github.com/0neGal/viper/issues/223) [0neGal/viper#165](https://github.com/0neGal/viper/issues/165) [R2NorthstarTools/FlightCore#288](https://github.com/R2NorthstarTools/FlightCore/issues/288) [R2Northstar/NorthstarLauncher#505](https://github.com/R2Northstar/NorthstarLauncher/issues/505)) unless I missed anything ^^"


in its current state viper is only useful when it works. which it doesnt on many occasions, if there was a way to search through all old tickets u could see this even more.

there are many occasions where viper just shits itself when mods are installed, or where it just breaks for no reason at all simply because it is viper.

from many screenshots of onegals answers there are also very clear issues on knowledge about topics such as wine/proton on linux.

both flightcore and vtol are better alternatives and i hate to admit it but at this point even klemms tether is coming into a better state then viper.

**Comment by EM4Volts** [comment]
to add to my above commend i want to also mention stuff  like this:
https://discord.com/channels/920776187884732556/942505193893945394/1232445332827406368

image

viper tells people to start stuff as administrator instead of the recommended solution of moving the game away from the ea folder. stuff like this shouldnt be in a recommended manager.

**Comment by 0neGal** [comment]
> ... however its Linux support is bare with launch support being non existant due to a lack of understanding of how its suppose to work and discontent with the proposed contributions of others.

I presume this is referring to the PR you made and the comments you made on the [Linux launch support PR](https://github.com/0neGal/viper/pull/116), if so I would disagree with me having a lack of understanding, my idea in it was simply to support using Wine executables directly, and being able to detect and use Steam prefixes and Proton installs, even if Proton is not supposed to be able to be run outside of the Steam environment (however I will admit at the time I valued using `steam://launch` much lower than using the Wine/Proton directly, for whatever reason).

I have also since then come to the conclusion that it'd both be easier to implement but also better for the user to simply use `steam://launch` and optionally a custom command set by the user, and have been meaning to get around to actually implementing that, however I've been busy, and have not prioritized it. On top of this, the large majority of users are not on Linux, so Viper missing launch support on Linux shouldn't be a valid reason by itself to remove it from the home page.

> No Viper contributor appears to be on the Northstar discord

I actually cant recall if I've ever mentioned it publically or only in DM with Gecko, but I have no interest in being on the Discord server, well, actually, it's that I have no interest in being on Discord. I've had my account banned multiple times for things that technically breaks ToS but doesn't affect anyone (third party clients and the like, nothing to do with being banned for any messages I've sent), and have had a lot of issues dealing with their support, and so forth. Overall my opinion of Discord as a whole is tainted and I dislike using it for anything ever. Were there to be a Matrix bridge or alike, then I would participate through that, but I also understand that setting one up and maintaining it is a bit of a pain more than anything, especially for just one user.

> ... making it impossible to give proper support to users when an issue specific to it appears.

Direct them to the issues page for Viper. There's not to my knowledge any major breaking bugs in Viper, that don't already have an open issue. In the sense that, I have no knowledge of such a bug existing, even if it does. If it did exist, and I did become aware of it, I would obviously fix it, until then, I can not. So any long standing bugs in Viper that do not have an open issue and keep going unfixed aren't as such due to neglect or not wanting to fix them, its entirely just because I don't know about them.

> viper is the sole cause of 99.6% of all issues that happen and are related to launchers

Great, then open an issue so that could be changed, I'm not going to scour a Discord server for people having issues with Viper or wait to be pinged a million times because someone had an issue and they're using Viper and someone decides to ping me.

> > There appears to be little to no communication between Northstar contributors and Viper contributors, leading to changes being made that break Viper until an end-user reports it.
> 
> I'd like to point out that too my knowledge, all breaking changes have been communicated by me via GitHub issues

As far as I'm aware, that's the case, it's not like there's literally no way to communicate with me, I have a [Twitter](https://twitter.com/0neGal) and [Mastodon](https://mstdn.social/@0negal) account in case communication outside of an issue is needed, or even email need it be. And of course mention me in an issue at any point in time and I'll usually make a reply within a couple hours or if busy around 1-2 days.

> there are many occasions where viper just shits itself when mods are installed, or where it just breaks for no reason at all simply because it is viper.

Again, I have no knowledge of issues like these, far from saying they don't exist, however were they to be handled by going "oh, you've an issue with Viper? either report it on Viper's issue page, or try and see if another launcher fixes it", instead of going "Viper moment, switch launcher, Viper bad", then that'd be appreciated.

The state of Viper is only where it is because nobody reports issues when they get them, which is quite counter productive, and only makes the situation worse.



> to add to my above commend i want to also mention stuff like this: https://discord.com/channels/920776187884732556/942505193893945394/1232445332827406368
> 
> image
> 
> viper tells people to start stuff as administrator instead of the recommended solution of moving the game away from the ea folder. stuff like this shouldnt be in a recommended manager.

We do not, that isn't a screenshot of Viper, none of the strings in that screenshot are present in any part of Viper's code, even attempting to search for the red color in the picture yields nothing. I have no clue what that is a screenshot of.

**Comment by EM4Volts** [comment]
> We do not, that isn't a screenshot of Viper, none of the strings in that screenshot are present in any part of Viper's code, even attempting to search for the red color in the picture yields nothing. I have no clue what that is a screenshot of.

on that note i wanna reject my statement and mention that then it might have been a skill issue on my side and this may be a screenshot of tmm, still i see "The state of Viper is only where it is because nobody reports issues when they get them, which is quite counter productive, and only makes the situation worse." as a thing that is just not a thing that works imo. basically everyday someone has to be recommended a launcher and when they are already using viper they get redirected to something else, every active person in the community has seen viper errors on atleast a 2-3 day cycle and knows they exist.

**Comment by 0neGal** [comment]
> every active person in the community has seen viper errors on atleast a 2-3 day cycle and knows they exist.

Yeah and that sucks, but without opening an issue, it cant exactly be fixed. And it would've been fixed, had an issue been opened.

**Comment by Jan200101** [comment]
> Proton installs, even if Proton is not supposed to be able to be run outside of the Steam environment

this is where your lack of understanding comes back.
Most if not all Proton builds (with notable exceptions being past Proton TKG builds) are linked against the steam runtime, running them in a system context will cause issues due to distros packaging different releases, renaming things, setting different options, etc.
As someone who is a Fedora maintainer and contributes to other distros when needed, you have completely misunderstood how the linux ecosystem works and why its such a great piece of pain for application developers which is why the Steam Runtime exists.

I've tried contributing and explaining these things, only to be met with a stubborn unwillingness to understand which is why I cannot recommend that any Linux user uses it.

**Comment by 0neGal** [comment]
> running them in a system context will cause issues due to distros packaging different releases, renaming things, setting different options, etc.

It *could* cause issues, the idea wasn't that it was perfect, and that it'd work for everybody, the idea was that you had the choice to select a Wine executable, and prefix, and on top of that, Viper could attempt to find an existing ones. I am well aware that doing it that way could cause issues, but it could also work for some, I didn't want to take away the option to use it like that, simply because it could cause issues.

And as mentioned, I no longer have intentions of having the Linux launch support use that.

**Comment by GeckoEidechse** [comment]
> I actually cant recall if I've ever mentioned it publically or only in DM with Gecko, but I have no interest in being on the Discord server, well, actually, it's that I have no interest in being on Discord.

Think it was only in DMs. But yeah, I'm aware of that and fully respect it ^^
On that note, we have a small Matrix server via https://matrix.to/#/#r2northstar:matrix.org but only announcement messages are bridged there (anything more would just kill the bridge cause of the high message frequency that Northstar sees)

&nsbp;

Regarding Viper and Linux support, should we just remove the mention of Linux support from Viper on the webpage until launching on Linux is supported in some form? That way there's less confusion from players when they find out that launching on Linux is not actually supported.
(On that note, we should change FlightCore's description to something like `Supports Windows, and Linux (Steam only). ` so that it's clear that FlightCore only supports launching via Steam).

&nsbp;

In general, I think the main take away from this discussion so far is that in cases where a player has issues with Viper, they should just be redirected to the Viper GitHub page (which is gonna be annoying for those that are confused when it comes to using GitHub). Those that make it through will at least hopefully get their issue be noticed and addressed accordingly.

**Comment by 0neGal** [comment]
> On that note, we have a small Matrix server via https://matrix.to/#/#r2northstar:matrix.org but only announcement messages are bridged there (anything more would just kill the bridge cause of the high message frequency that Northstar sees)

Totally understandable! :)

> Regarding Viper and Linux support, should we just remove the mention of Linux support from Viper on the webpage until launching on Linux is supported in some form?

I think at the current stage that Viper's Linux support is in, it should at least be made clear that its not fully supported due to it, removing it completely may be more confusing, implying that Viper only works on Windows, so something like "Supports Windows and Linux (except launching the game on Linux)" might be better, albeit slightly wordy...

However, I can make time and whip together functional Linux launch support semi-quickly, and then after testing, it'd just be up to i18n to get merged and released. So it might be more of a hassle to remove it, only to add it right back? Up to you to contemplate that part!

I've only been putting it off for this long due to not prioritizing it, I've physically had time to do it :p

**Comment by GeckoEidechse** [comment]
> I think at the current stage that Viper's Linux support is in, it should at least be made clear that its not fully supported due to it, removing it completely may be more confusing, implying that Viper only works on Windows, so something like "Supports Windows and Linux (except launching the game on Linux)" might be better, albeit slightly wordy...

Maybe something like `Supports Windows and Linux (mod install only)` or `Supports Windows and partially Linux`?

> However, I can make time and whip together functional Linux launch support semi-quickly, and then after testing, it'd just be up to i18n to get merged and released. 

That would be amazing :D

**Comment by 0neGal** [comment]
> Maybe something like `Supports Windows and Linux (mod install only)` or `Supports Windows and partially Linux`?

I think the latter is probably the better one? "mod install only" kind of implies it only does Thunderstore stuff, at least to me anyway...

"mostly" might however be a better word than "partially"?

**Comment by EM4Volts** [comment]
> I actually cant recall if I've ever mentioned it publically or only in DM with Gecko, but I have no interest in being on the Discord server, well, actually, it's that I have no interest in being on Discord. I've had my account banned multiple times for things that technically breaks ToS but doesn't affect anyone (third party clients and the like, nothing to do with being banned for any messages I've sent), and have had a lot of issues dealing with their support, and so forth. Overall my opinion of Discord as a whole is tainted and I dislike using it for anything ever. Were there to be a Matrix bridge or alike, then I would participate through that, but I also understand that setting one up and maintaining it is a bit of a pain more than anything, especially for just one user.


so just for me to get this right, and understand it.

you have no interest in activly participating in this community, but want to make a mod manager and then are angry when people dont report issues to u because u are nowhere to be found and most people dont use github

**Comment by 0neGal** [comment]
No, I have no interest in using Discord, that doesn't mean I have no interest in participating with the community.

If you're saying "not being on Discord, but mostly everywhere else, and very willing to fix bugs when reported" is the same as "nowhere to be found", sure, but I personally don't see those as the same thing.

**Comment by EM4Volts** [comment]
Screenshot_2024-05-29_120345

@0neGal here is a screenshot just in a ticket from viper.

**Comment by 0neGal** [comment]
Quite off topic to post it here, instead of creating an actual issue on the Viper's repo, but this should actually be a simple fix, and assuming the issue is what I think it is, it should be fixed with [`9f7a4cf`](https://github.com/0neGal/viper/commit/9f7a4cf5a7ff45ebad524aa7ec6edc60cd84cfb1)

Temporary fix would be to delete `enabledmods.json` or at least, put just `[]` inside it, I do wonder what the contents of it is...

**Comment by Jan200101** [comment]
> Quite off topic to post it here, instead of creating an actual issue on the Viper's repo

I disagree that this is offtopic
tickets are always being opened for bugs with Viper or r2mm that we cannot recreate, can't report without any information around it and can't act on beyond telling them to switch to an alternative.

Its good that its fixed now, but its not in any release so people are inevitably going to run into it again.

**Comment by 0neGal** [comment]
I'm not saying this is off topic to be reported, I'm saying it's off topic to report it inside this issue that has nothing to do with this bug, and it'd have been more appropriate to create an issue on the Viper repo. :p

> tickets are always being opened for bugs with Viper or r2mm that we cannot recreate, can't report without any information

No matter how much information you've available to report, it's still better than posting it in a comment on an issue that first of all is outside of Viper's repo, and second of all, has nothing to do with the bug.

**Comment by EM4Volts** [comment]
> I'm not saying this is off topic to be reported, I'm saying it's off topic to report it inside this issue that has nothing to do with this bug, and it'd have been more appropriate to create an issue on the Viper repo. :p
> 
> > tickets are always being opened for bugs with Viper or r2mm that we cannot recreate, can't report without any information
> 
> No matter how much information you've available to report, it's still better than posting it in a comment on an issue that first of all is outside of Viper's repo, and second of all, has nothing to do with the bug.

cool. and this pr has nothing todo with the bugs and tickets ur software create, 

you dont seem to want to participate with the northstar community from what it seems beside making fixes to a mod manager that has been made redundant. 
you dont wanna join the discord which is where northstar arguably happens. alot of stuff happens in the research channels there, alot of stuff happens in other channels. asking everyone to make issues on github is not a solution and wont fix the problem we have with viper being recommended

**Comment by 0neGal** [comment]
> cool. and this pr has nothing todo with the bugs and tickets ur software create,

Which was my point .w.

> you dont seem to want to participate with the northstar community from what it seems

> you dont wanna join the discord which is where northstar arguably happens

I don't want to be forced to use a platform that I fundamentally disagree with using, Discord as a company and an app aren't particular great in any way shape or form, it just so happens that it has become the norm/standard, unfortunately. 

> asking everyone to make issues on github is not a solution and wont fix the problem we have with viper being recommended

The primary reason you want to remove Viper from the website is because it causes the majority of your issues, issues that I've not been made aware of, which is the entire reason they continue to exist. Were they to be reported, they'd be fixed, were they to be fixed, you'd have less reports to make and less issues to deal with. It's really just a self perpetuating problem, you don't report the issues, they remain unfixed, so when new issues arise, the old issues continue to also exist, leading you to just have more and more issues that you don't report.

I'm not asking "everyone" to make GitHub issues, I'm asking people to either not complain about bugs they don't want to report, or that they report said bugs.

**Comment by EladNLG** [comment]
Gonna leave some input.

Bugs cannot be fixed unless they are reported, that is true. However, helpers find it much more convenient to tell people to use _actually stable software_ than go on a github repo and submit an issue (and until then they cannot help the user anyways.)

Viper issues are so common, that bothering to create an issue for each one proves too cumbersome (Additionally, helpers are NOT developers and may not have programming experience, so they might be unable to distinguish between different issues.), and with _hundreds_ of tickets to go through, saving time is high priority.

However, most mod manager developers are active in the discord and are able to catch bugs from user tickets, and create GitHub issues for them on their own, since we can easily ping them and bring these bugs to their attention.

Whilst you choosing to not use Discord is fine - _we are not going to change our process, especially not by adding a time-consuming process, for the sake of one program/individual._ As such, by not using Discord, you **give up these potential bug fixes.**

This is why your mod manager is unstable, and causes most tickets. Whilst your choice to not use Discord is perfectly fine, we are not going to modify our process for the sake of one program, and are not going to make our helpers submit github issues for each time your program causes an issue. That's not their ""job"".

I'm neutral on this change. I don't care otherwise.

**Comment by 0neGal** [comment]
With this in mind I'm not entirely certain how we can even move forward, as we're clearly in a deadlock here, I won't be forced to use Discord, and it's too cumbersome for you to report bugs.

I don't really personally care if you setup a command to easily send a Discord conversation to me in some form, or if it's over a GitHub issue, the latter seems unlikely for you to agree upon, and the prior also seems unlikely, as someone would have to make this command work.

Any suggestions? Beyond me using Discord or simply removing Viper from the website.

**Comment by EM4Volts** [comment]
> With this in mind I'm not entirely certain how we can even move forward, as we're clearly in a deadlock here, I won't be forced to use Discord, and it's too cumbersome for you to report bugs.
> 
> I don't really personally care if you setup a command to easily send a Discord conversation to me in some form, or if it's over a GitHub issue, the latter seems unlikely for you to agree upon, and the prior also seems unlikely, as someone would have to make this command work.
> 
> Any suggestions? Beyond me using Discord or simply removing Viper from the website.

my honest suggestion is to merge this pr and remove viper from the site. there is no better solution at this point.
you dont want to use discord,
we wont change the way fundamental things work just because.

there are two other mod managers that work and are superior in basically each way, so there is no incentive to keep viper on the site.

**Comment by Jan200101** [comment]
I do have an alternative to remove Viper from the website: do what Matrix does.
https://matrix.org/ecosystem/clients/

We can provide a list of all available launchers (which would also include things such as [Tether](https://github.com/Klemmbaustein/TetherInstaller)) with so called "featured" (naming is up to debate) launchers at the top (we could also hide all non featured launchers behind a drop-down so that only powerusers can find it).

In the Discord Tickets we can explicitly deny anything that isn't featured to remove the headache from helpers.

This would allow Viper to continue being on the website without it having to be endorsed by Northstar.
This solution would allow Viper to continue being on the website while not

**Comment by 0neGal** [comment]
> we wont change the way fundamental things work just because.

Neither will I, unfortunately. :p

> I do have an alternative to remove Viper from the website: do what Matrix does.
https://matrix.org/ecosystem/clients/

This actually sounds like a sound solution, it would also help with newer launchers, and more experimental ones, etc.

Ideally in such a situation there'd be able to be a more descriptive description about the launcher, listing what frameworks it's built with, and whether it's meant for power users or simply to be easy to use.

Although of course 1 launcher can't take up the entire screen with its description, perhaps clicking them would show a list of features, similar to the [existing launcher list.](https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/northstar-installers)

Just overall, make it clear what the differences are.

> In the Discord Tickets we can explicitly deny anything that isn't featured to remove the headache from helpers.

It might be best to still allow tickets to be created with issues, albeit close them if the helper has no idea what the issue could be, directing towards the relevant links for that launcher. Some errors that arise, especially the ones with actual error messages may be very easily diagnosable for a helper.

That, or perhaps ask the user to select which launcher they're using when making the ticket, and were they to select something that's not officially endorsed, then they'd be redirected to the relevant links.

Either is better than denying all support frankly. Speaking for both Viper but also any other launcher that would be on this list.

**Comment by GeckoEidechse** [comment]
> I do have an alternative to remove Viper from the website: do what Matrix does.
> https://matrix.org/ecosystem/clients/

Personally I like this idea a lot.

&nbsp;

As a sidenote, we don't have too many tickets on Northstar atm, so I put out a message to helpers to just ping me on any Viper related ticket and I'll forward a bug report ^^

**Comment by GeckoEidechse** [comment]
Superseded by #81

**Pull request closed without merging**
