### PR TITLE
Add attribution notice for IP2Location

### PR DESCRIPTION
**Pull request by pg9182**
As per the license agreement.

### CODE REVIEW

**Comment by emma-miler** [comment]
Might be good to add a separate header/section for licenses? Looks a bit off right now, at least in my opinion

**Comment by pg9182** [comment]
Idk; I think it looks off to have a header for a single line of text too.

**Comment by emma-miler** [comment]
Fair. Would having a separate page linked in the footer be sufficient to satisfy the license? If so, i think that would probably be our best option

**Comment by pg9182** [comment]
I think adding it to the credits page is sufficient, although it wouldn't hurt to add it to the server browser page too. I don't think a line of small text at the bottom of the credits page is any better or worse than a textual link in a footer of icons. I'm satisfied with the way I did it, but I don't have strong feelings on it.

**Comment by emma-miler** [comment]
Alright, merging it in this state and we can always revisit it later

**Pull request merged**
