### PR TITLE
Commit directly instead of making a PR in the scraping actions

### PR DESCRIPTION
**Pull request by ASpoonPlaysGames**
There is a chance that branch protection rules will ruin this, but it [worked on my fork](https://github.com/ASpoonPlaysGames/NorthstarTF/actions/runs/12340598381)

### CODE REVIEW

**Review by GeckoEidechse — APPROVED** [review]
From a quick look this should be fine. I guess we just try and see if it works ^^

**Comment by GeckoEidechse** [comment]
(would prefer long form args btw cause they are more readable but you already tested it and I don't wanna have to retest to make sure I didn't add a typo or something)

**Comment by ASpoonPlaysGames** [comment]
Probably a good idea to make a commit that modifies some of the data and then run the workflow manually to fix it, see if it works properly

**Comment by GeckoEidechse** [comment]
Yeah. This review I gave above should count towards the flow so I'm just running the review scraper manually now and see if it works. It just takes like half an hour to finish lol

**Comment by ASpoonPlaysGames** [comment]
> It just takes like half an hour to finish lol

This is why I tested with the other scraper first, takes a few seconds

**Comment by GeckoEidechse** [comment]
Failed for branch protection reasons :c

**Pull request merged**
