### PR TITLE
Change `Installation` to `Launchers`, add clarification subtext

### PR DESCRIPTION
**Pull request by itscynxx**
Pretty sure I changed the right line, hopefully I did

A lot of new users tend to get confused and think all 4 "main" ways to install Northstar are different clients with different servers, so hopefully clarifying that it's _different ways to install the same Northstar_ can cut down on at least a couple cases where people ask about it in the discord

Completely open to suggestions, edits, or thoughts

### CODE REVIEW

**Comment by ASpoonPlaysGames** [comment]
Perhaps "Installation methods" could be better? Idk

**Comment by CooldudePUGS** [comment]
> Perhaps "Installation methods" could be better? Idk

Maybe "Installation methods for Northstar", but I'm not entirely sure about just "Installation methods" because I feel like to an end user that doesn't read/know what Northstar is, it might still confuse them, people see "Installation" and assume they're all different versions and "Installation methods" might still seem that way to them, but maybe I'm overthinking it

Issue is it's hard to really tell because to people that might want to change this to make more sense, "Installation" already makes it really straight forward what it is lol

**Review by GeckoEidechse — COMMENTED** [review]
Maybe add a screenshot that shows the change visually ^^

**Comment by itscynxx** [comment]
One year anniversary :poggies:

I'm going to close this as
1. I feel the section name shouldn't be changed
2. My fork is messed up
3. I don't want to deal with conflict solving even though this is easy

**Pull request closed without merging**
