### PR TITLE
Change order of installers to FlightCore, VTOL, Viper, Manual on Northstar.tf

### PR DESCRIPTION
**Pull request by CooldudePUGS**
FlightCore generally works better for end users, as well as being actively updated and maintained. Viper is still a good mod manager, and I think it should stay as an option (unless somehow we come to a conclusion and one centralized launcher)

I don't mean to cause any controversy or ill will towards 0negal with this change, and hope that it won't happen

### CODE REVIEW

**Comment by BigSpice** [comment]
bump

**Comment by GeckoEidechse** [comment]
Fine by me. Probably best for someone else to merge it though cause given that I'm one of the main authors of FlightCore, there's a bit of a conflict of interest here :P

**Comment by ASpoonPlaysGames** [comment]
> Probably best for someone else to merge it though cause given that I'm one of the main authors of FlightCore, there's a bit of a conflict of interest here :P

It would appear that nobody has any problems with this, given that it has been 2 weeks (and it has been mentioned in discord like 5 times now) so honestly feel free to just merge it

**Review by GeckoEidechse — APPROVED** [review]

**Comment by GeckoEidechse** [comment]
Merging myself cause as said there has been no opposition on Discord in regards to this change.

If anyone does take issue with this change, please reach out, I'm more than happy to revert again if need be ^^

**Pull request merged**
